data_organizer_task:
  description: >
    Organize the data about company {company_name} from multiple sources into a structured JSON format that can be used by an analyst to build a report on this company.
    You have access to the following data sources:
    {company_sources}
  expected_output: >
    A structured JSON format of the data.
  agent: data_organizer

research_task:
  description: >
    Conduct a thorough research about company {company_name}.
    Make sure you find any interesting and relevant information to fill out the following sections of an investment report: {sections}.
    The information must be up to date given the current year is {current_year}.
  expected_output: >
    A list with 10 items and associated website link of the most relevant information about company {company_name} for each of the report sections.
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into full sections of an investment report.
    Make sure the report is detailed and contains any and all relevant information.
    For today, focus only on the following sections: {sections}.
    For your reference, you have access to the following report from a different company, which we can use to gauge format and style: {reference_sources}.
  expected_output: >
    A fully fledged investment report with the following sections: {sections}.
    Formatted as markdown without '```'
  agent: reporting_analyst
