data_organizer_task:
  description: >
    Organize the data about company {company_name} from multiple sources into a structured JSON format that can be used by an analyst to build a report on this company.
    You have access to the following data sources:
    {company_sources}
  expected_output: >
    A structured JSON format of the data.
  agent: data_organizer

overview_section_writer_task:
  description: >
    Write a detailed section for an investment report about company {company_name}.
    You have access to data about {company_name} provided by the data organizer task and the ability to search and browse the web for additional information.
    Below are templates for what a full report looks like for your reference:
    {reference_sources}
    You are responsible for writing the Overview section of the report.
  expected_output: >
    A detailed Overview section for an investment report about company {company_name}.
  agent: section_writer

why_interesting_section_writer_task:
  description: >
    Write a detailed section for an investment report about company {company_name}.
    You have access to data about {company_name} provided by the data organizer task and the ability to search and browse the web for additional information.
    Below are templates for what a full report looks like for your reference:
    {reference_sources}
    You are responsible for writing the Why Interesting section of the report.
  expected_output: >
    A detailed Why Interesting section for an investment report about company {company_name}.
  agent: section_writer

