data_organizer_task:
  description: >
    Organize the data about company {company_name} from multiple sources into a structured JSON format that can be used by an analyst to build a report on this company.
    You have access to the following data sources:
    {company_sources}
  expected_output: >
    A structured JSON format of the data.
  agent: data_organizer

research_task:
  description: >
    Conduct a thorough research about company {company_name}.
    Make sure you find any interesting and relevant information to fill out the following sections of an investment report: {sections}.
    The information must be up to date given the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about company {company_name} for each of the report sections.
  agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
